from huggingface_hub import login

login("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")
TRAIN_FILE = "../train.csv"
VALID_FILE = "../valid.csv"
TEST_FILE = "../test.csv"

MODEL_PATH = "../models/origin"

LORA_RANK = 64
LORA_DROPOUT = 0.1
LORA_ALPHA = 32
LORA_BIAS = 'none'
LORA_TASK_TYPE = "CAUSAL_LM"

WANDB_TRAINING_TITLE = "TRAINING FINE TUNE LLAMA3.1 INSTRUCT 8B"
WANDB_VALID_TITLE = "TRAINING FINE TUNE LLAMA3.1 INSTRUCT 8B"

PER_DEVICE_TRAIN_BATCH_SIZE = 8
PER_DEVICE_VALID_BATCH_SIZE = 16

GRADIENT_ACCUMULATION_STEPS = 2
LEARNING_RATE = 2e-4

# MAX_LENGTH = 39219
MAX_LENGTH = 8198
MAX_LENGTH_GAP = 1024
